package interfaz;

import interfaz.*;
import dominio.*;
import java.util.Enumeration;
import java.util.Observer;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

public class AltaPostulante extends javax.swing.JFrame {

    public AltaPostulante(Sistema sis) {
        initComponents();
        modelo = sis;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formatoTrabajo = new javax.swing.ButtonGroup();
        formatoPostulante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombrePostulante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cedulaPostulante = new javax.swing.JTextField();
        direccionPostulante = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        telefonoPostulante = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mailPostulante = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        linkedinPostulante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        radioRemoto = new javax.swing.JRadioButton();
        radioPresencial = new javax.swing.JRadioButton();
        radioMixto = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alta de postulante");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nombre:");

        nombrePostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePostulanteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cédula:");

        cedulaPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaPostulanteActionPerformed(evt);
            }
        });

        direccionPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionPostulanteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Dirección:");

        telefonoPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoPostulanteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Teléfono:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Mail:");

        mailPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailPostulanteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Linkedin");

        linkedinPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedinPostulanteActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Formato");

        formatoTrabajo.add(radioRemoto);
        radioRemoto.setText("Remoto");
        radioRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRemotoActionPerformed(evt);
            }
        });

        formatoTrabajo.add(radioPresencial);
        radioPresencial.setText("Presencial");
        radioPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPresencialActionPerformed(evt);
            }
        });

        formatoTrabajo.add(radioMixto);
        radioMixto.setText("Mixto");
        radioMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMixtoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formatoPostulanteLayout = new javax.swing.GroupLayout(formatoPostulante);
        formatoPostulante.setLayout(formatoPostulanteLayout);
        formatoPostulanteLayout.setHorizontalGroup(
            formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatoPostulanteLayout.createSequentialGroup()
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formatoPostulanteLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(formatoPostulanteLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(69, 69, 69)
                        .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formatoPostulanteLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrePostulante)
                                    .addComponent(cedulaPostulante)
                                    .addComponent(direccionPostulante)
                                    .addComponent(telefonoPostulante)
                                    .addComponent(mailPostulante)
                                    .addComponent(linkedinPostulante)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formatoPostulanteLayout.createSequentialGroup()
                                        .addComponent(radioRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(radioPresencial, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addGap(64, 64, 64)
                                        .addComponent(radioMixto, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))))
                            .addGroup(formatoPostulanteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        formatoPostulanteLayout.setVerticalGroup(
            formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formatoPostulanteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombrePostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cedulaPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(direccionPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telefonoPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(mailPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(linkedinPostulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(radioRemoto)
                        .addComponent(radioPresencial)
                        .addComponent(radioMixto)))
                .addGap(33, 33, 33)
                .addGroup(formatoPostulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSiguiente))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(formatoPostulante);
        formatoPostulante.setBounds(10, 20, 670, 480);

        setBounds(0, 0, 706, 566);
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePostulanteActionPerformed

    private void cedulaPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaPostulanteActionPerformed

    private void direccionPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionPostulanteActionPerformed

    private void telefonoPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoPostulanteActionPerformed

    private void mailPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailPostulanteActionPerformed

    private void linkedinPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedinPostulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkedinPostulanteActionPerformed

    private void radioRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRemotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRemotoActionPerformed

    private void radioMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMixtoActionPerformed

    private void radioPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPresencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPresencialActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String cedula = this.cedulaPostulante.getText();
        String nombre = this.nombrePostulante.getText();
        String direccion = this.direccionPostulante.getText();
        String telefono = this.telefonoPostulante.getText();
        String mail = this.mailPostulante.getText();
        String linkedin = this.linkedinPostulante.getText();

        String selectedRadioButton = "";
        if (radioRemoto.isSelected()) {
            selectedRadioButton = "remoto";
        } else if (radioPresencial.isSelected()) {
            selectedRadioButton = "presencial";
        } else if (radioMixto.isSelected()) {
            selectedRadioButton = "mixto";
        }
        String[] valores = {nombre, cedula, direccion, telefono, mail, linkedin, selectedRadioButton};
        boolean validos = true;
        for (int i = 0; i < valores.length && validos; i++) {
            if (valores[i].strip().equals("") || valores[i] == null) {
                validos = false;
                JOptionPane.showMessageDialog(AltaPostulante.this, "Error: Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        int cedulaInt = Utils.convertirAEntero(cedula);
        if (validos) {
            if (cedulaInt == -1) {
                JOptionPane.showMessageDialog(AltaPostulante.this, "Error: Ingrese cedula válida", "Error", JOptionPane.ERROR_MESSAGE);
                validos = false;
            } else if (!modelo.cedulaEsUnica(cedulaInt)) {
                JOptionPane.showMessageDialog(AltaPostulante.this, "Ya existe una persona con la cedula indicada. Verifique la misma", "Error", JOptionPane.ERROR_MESSAGE);
                validos = false;

            }
        }
        if (validos) {
            Postulante post = new Postulante(nombre, cedulaInt, direccion, telefono, mail, linkedin, selectedRadioButton);
            VentanaTematicasPostulante nuevaVentana = new VentanaTematicasPostulante(modelo, post);
            nuevaVentana.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField cedulaPostulante;
    private javax.swing.JTextField direccionPostulante;
    private javax.swing.JPanel formatoPostulante;
    private javax.swing.ButtonGroup formatoTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField linkedinPostulante;
    private javax.swing.JTextField mailPostulante;
    private javax.swing.JTextField nombrePostulante;
    private javax.swing.JRadioButton radioMixto;
    private javax.swing.JRadioButton radioPresencial;
    private javax.swing.JRadioButton radioRemoto;
    private javax.swing.JTextField telefonoPostulante;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
