/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.Evaluador;
import dominio.Sistema;
import dominio.Utils;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author alumnoFI
 */
public class VentanaRegistroEvaluador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroEvaluador
     */
    public VentanaRegistroEvaluador(Sistema mod) {
        initComponents();
        modelo = mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreEvaluador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cedulaEvaluador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccionEvaluador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spinnerAno = new javax.swing.JSpinner();
        buttonRegistrarEvaluador = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registro de evaluador");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 24, 246, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(29, 70, 58, 20);

        nombreEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEvaluadorActionPerformed(evt);
            }
        });
        jPanel1.add(nombreEvaluador);
        nombreEvaluador.setBounds(221, 68, 337, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cedula:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(29, 108, 49, 20);

        cedulaEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaEvaluadorActionPerformed(evt);
            }
        });
        jPanel1.add(cedulaEvaluador);
        cedulaEvaluador.setBounds(221, 106, 337, 26);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(29, 146, 65, 20);

        direccionEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionEvaluadorActionPerformed(evt);
            }
        });
        jPanel1.add(direccionEvaluador);
        direccionEvaluador.setBounds(221, 144, 337, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Año de ingreso:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(29, 184, 104, 20);

        SpinnerNumberModel spinner = new SpinnerNumberModel(1930, 1930, 2023, 1);
        spinnerAno.setModel(spinner);
        jPanel1.add(spinnerAno);
        spinnerAno.setBounds(221, 182, 337, 26);

        buttonRegistrarEvaluador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegistrarEvaluador.setText("Registrar");
        buttonRegistrarEvaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarEvaluadorActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRegistrarEvaluador);
        buttonRegistrarEvaluador.setBounds(465, 237, 93, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEvaluadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEvaluadorActionPerformed

    private void cedulaEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaEvaluadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaEvaluadorActionPerformed

    private void direccionEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionEvaluadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionEvaluadorActionPerformed

    private void buttonRegistrarEvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarEvaluadorActionPerformed
//        nombreEvaluador.setText("");
//        cedulaEvaluador.setText("");
//        direccionEvaluador.setText("");
//        spinnerAno.getModel().setValue(1930);
        String nombre = nombreEvaluador.getText();
        String cedula = cedulaEvaluador.getText();
        String direccion = direccionEvaluador.getText();
        int valorSpinner = (int) spinnerAno.getValue();
        String valorSpinnerString = valorSpinner+"";
        String[] valores = {nombre, cedula, direccion, valorSpinnerString};
        boolean validos = true;
        for (int i = 0; i < valores.length && validos; i++) {
            if (valores[i].strip().equals("") || valores[i] == null) {
                validos = false;
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        int cedulaInt = Utils.convertirAEntero(cedula);
        if (validos) {
            if (cedulaInt == -1) {
                JOptionPane.showMessageDialog(this, "Ingrese cedula válida", "Error", JOptionPane.ERROR_MESSAGE);
                validos = false;
            } else if (!modelo.cedulaEsUnica(cedulaInt)) {
                JOptionPane.showMessageDialog(this, "Ya existe una persona con la cedula indicada. Verifique la misma", "Error", JOptionPane.ERROR_MESSAGE);
                validos = false;
            }
        }
        if(validos){
            Evaluador eval = new Evaluador(nombre,cedulaInt, direccion, valorSpinner);
        }
    }//GEN-LAST:event_buttonRegistrarEvaluadorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrarEvaluador;
    private javax.swing.JTextField cedulaEvaluador;
    private javax.swing.JTextField direccionEvaluador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreEvaluador;
    private javax.swing.JSpinner spinnerAno;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
